/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.bluetoothkeyboardapp;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int clear_button=0x7f030005;
        public static final int connect_button=0x7f030002;
        public static final int device_text=0x7f030003;
        public static final int input_edit_text=0x7f030004;
        public static final int scan_button=0x7f030001;
        public static final int send_button=0x7f030006;
        public static final int status_text=0x7f030000;
    }
    public static final class layout {
        public static final int activity_main=0x7f020000;
    }
}
